name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --parallel
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/debug/*.apk    
    - name: Version Bump
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle
        versionCode: ${{ github.run_number }}
  release:
    name: release to GitHub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 17
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag
          draft: true
          files: |
            app/build/outputs/apk/debug/app-arm64-v8a-debug.apk 
        env:
          GITHUB_TOKEN: ${{ secrets.KYUBI_TOKEN }}
